#!/usr/bin/env bash
XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/flatpak/exports/share:/home/dunossauro/.local/share/flatpak/exports/share"
XDG_CONFIG_DIRS="/etc/xdg"

# Kyboard config
setxkbmap -model abnt -layout us -variant intl

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Envvars
if [ -e ~/.bashrc.envvars ] ; then
   source ~/.bashrc.envvars
fi

# Secrets
if [ -e ~/.bashrc.secrets ] ; then
   source ~/.bashrc.secrets
fi

# Python Env
if [ -e ~/.bashrc.python_env ] ; then
   source ~/.bashrc.python_env
fi


# Aliases
if [ -e ~/.bashrc.aliases ] ; then
   source ~/.bashrc.aliases
fi

# Functions
if [ -e ~/.bashrc.functions ] ; then
   source ~/.bashrc.functions
fi

# Current project
if [ -e ~/.bashrc.project ] ; then
   source ~/.bashrc.project
fi

# Created by `pipx` on 2023-12-07 12:19:00
export PATH="$PATH:/home/dunossauro/.local/bin"
