#!/usr/bin/env python3
from subprocess import check_output
response = check_output('upower -i /org/freedesktop/UPower/devices/keyboard_dev_D5_93_0E_DE_F2_F8', shell=True).decode().split('\n')
if '    present:             yes' in response:
    print(response[12].split()[-1])
