#!/bin/bash

artist=$(playerctl metadata artist -p youtubemusic,strawberry 2>&1)
title=$(playerctl metadata title -p youtubemusic,strawberry 2>&1)
album=$(playerctl metadata album -p youtubemusic,strawberry 2>&1)

if [[ "$title" == *"No players found"* ]]; then
    exit 0
fi

if [[ -n "$artist" && -n "$title" ]]; then
    echo "🎵 $artist - $title (${album:-Sem Álbum})"
fi
