---
- name: Pcotes AUR
  hosts: localhost

  tasks:
    - name: Instalação paru
      kewlfft.aur.aur:
        name: paru-bin
        state: present
        use: makepkg

    - name: Instalação obs
      kewlfft.aur.aur:
        use: paru
        name: obs-studio-tytan652
        state: present

    - name: Instalação dotdrop (paru)
      kewlfft.aur.aur:
        use: paru
        name: dotdrop
        state: present

    - name: Ajusta dotdrop para nome do host
      shell: sed -i 's/melville/archlinux/' /home/vagrant/dotfiles/config.yaml
      # TODO: Ajustar isso

    - name: configura dotfiles
      shell: dotdrop --cfg=/home/vagrant/dotfiles/config.yaml install -f
      # TODO: Ajustar isso

    - name: Instalação waterfox (paru)
      kewlfft.aur.aur:
        use: paru
        name: waterfox-bin
        state: present
