---
- name: Pcotes AUR
  hosts: localhost
  tasks:
    - name: Instalação paru
      kewlfft.aur.aur:
        name: paru-bin
        state: present
        use: makepkg

    - name: Instalação dotdrop (paru)
      kewlfft.aur.aur:
        use: paru
        name: dotdrop
        state: present

    - name: Ajusta dotdrop para nome do host
      shell: sed -i 's/melville/{{ inventory_hostname }}/' dotfiles/config.yaml

    - name: configura dotfiles
      shell: dotdrop install

    - name: Instalação waterfox (paru)
      kewlfft.aur.aur:
        use: paru
        name: waterfox-bin
        state: present
