---
- name: Instalação inicial do sistema
  hosts: localhost


  tasks:
    - name: Instalação devel
      become: yes
      package:
        name: base-devel
        state: present

    - name: Instalação cmake
      become: yes
      package:
        name: cmake
        state: present

    - name: Instalação git
      become: yes
      package:
        name: git
        state: present

    - name: Instalação nano
      become: yes
      package:
        name: nano
        state: present

    - name: Instalação eza
      become: yes
      package:
        name: eza
        state: present

    - name: Instalação bat
      become: yes
      package:
        name: bat
        state: present

    - name: Instalação libvterm
      become: yes
      package:
        state: present
        name: libvterm

    - name: Instalação ttf-dejavu
      become: yes
      package:
        state: present
        name: ttf-dejavu

    - name: instalação emacs
      become: yes
      package:
        state: present
        name: emacs

    - name: Cópia dotfiles
      git:
        repo: https://codeberg.org/dunossauro/dotfiles.git
        dest: dotfiles

    - name: chown dotfiles
      become: yes
      shell: chown -R vagrant:vagrant .
      # TODO: Ajustar isso

    - name: Instalação xorg
      become: yes
      package:
        name: xorg
        state: present

    - name: Instalação qtile
      become: yes
      package:
        name: qtile
        state: present

    - name: Instalação lightdm
      become: yes
      package:
        name: lightdm
        state: present

    - name: Instalação lightdm-gtk-greeter
      become: yes
      package:
        name: lightdm-gtk-greeter
        state: present

    - name: Inicialização do greeter
      become: yes
      ansible.builtin.systemd_service:
        enabled: true
        name: lightdm

    - name: Instalação pipewire
      become: yes
      package:
        name: pipewire
        state: present

    - name: Instalação pipewire-alsa
      become: yes
      package:
        name: pipewire-alsa
        state: present

    - name: Instalação pipewire-pulse
      become: yes
      package:
        name: pipewire-pulse
        state: present

    - name: Instalação pipewire-jack
      become: yes
      package:
        name: pipewire-jack
        state: present

    - name: Ativando pipewire
      ansible.builtin.systemd_service:
        name: pipewire
        enabled: true
        scope: user

    - name: Instalação networkmanager
      become: yes
      package:
        name: networkmanager
        state: present

    - name: Instalação network-manager-applet
      become: yes
      package:
        name: network-manager-applet
        state: present

    - name: Ativando NetworkManager
      ansible.builtin.systemd_service:
        name: NetworkManager
        enabled: true
        scope: user

    - name: Instalação terminator
      become: yes
      package:
        name: terminator
        state: present

    - name: Instalação xonsh
      become: yes
      package:
        name: xonsh
        state: present

    - name: Configuração xonsh
      become: yes
      shell: chsh -s /usr/bin/xonsh vagrant
      # TODO: Ajustar isso

    - name: Configuração bpytop
      become: yes
      package:
        name: bpytop
        state: present
