---
- name: Instalação inicial
  hosts: localhost


  tasks:
    - name: Instalação devel
      become: yes
      package:
        name: base-devel
        state: present

    - name: Instalação nano
      become: yes
      package:
        name: nano
        state: present

    - name: Instalação eza
      become: yes
      package:
        name: eza
        state: present

    - name: Instalação bat
      become: yes
      package:
        name: bat
        state: present

    - name: Instalação libvterm
      become: yes
      package:
        state: present
        name: libvterm

    - name: Instalação ttf-dejavu
      become: yes
      package:
        state: present
        name: ttf-dejavu

    - name: instalação emacs
      become: yes
      package:
        state: present
        name: emacs

    - name: Cópia dotfiles
      git:
        repo: https://codeberg.org/dunossauro/dotfiles.git
        dest: dotfiles

    - name: Instalação xorg
      become: yes
      package:
        name: xorg
        state: present

    - name: Instalação qtile
      become: yes
      package:
        name: qtile
        state: present

    - name: Instalação lightdm
      become: yes
      package:
        name: lightdm
        state: present

    - name: Instalação lightdm-gtk-greeter
      become: yes
      package:
        name: lightdm-gtk-greeter
        state: present

    - name: Inicialização do greeter
      become: yes
      ansible.builtin.systemd_service:
        enabled: true
        name: lightdm

    - name: Instalação terminator
      become: yes
      package:
        name: terminator
        state: present

    - name: Instalação xonsh
      become: yes
      package:
        name: xonsh
        state: present

    - name: Configuração xonsh
      shell: chsh -s $(which xonsh)
