---
- name: Instalação das ferramentas de programar
  hosts: localhost

  tasks:
    - name: Instalação act
      become: yes
      package:
        name: act
        state: present

    - name: Instalação podman
      become: yes
      package:
        name: podman
        state: present

    - name: Instalação podman-compose
      become: yes
      package:
        name: podman-compose
        state: present
