---
- hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: play1

- name: aur
  import_playbook: aur.yml

- name: coding
  import_playbook: coding.yml

# TODO: Ajustar isso
#import_playbook: gui.yml
#import_playbook: python.yml
#import_playbook: work.yml
